//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Musaranha.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pagamento
    {
        public int CodPagamento { get; set; }
        public int CodFuncionario { get; set; }
        public System.DateTime DtPagamento { get; set; }
        public int MesReferencia { get; set; }
        public int AnoReferencia { get; set; }
        public decimal Valor { get; set; }
    
        public virtual Funcionario Funcionario { get; set; }
    }
}
