//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Musaranha.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Telefone
    {
        public int CodPessoa { get; set; }
        public string NumTelefone { get; set; }
    
        public virtual Pessoa Pessoa { get; set; }
    }
}
