//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Musaranha.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VendaProduto
    {
        public int CodVenda { get; set; }
        public int CodProduto { get; set; }
        public string Unidade { get; set; }
        public double Quantidade { get; set; }
        public decimal PrecoUnitario { get; set; }
    
        public virtual Produto Produto { get; set; }
        public virtual Venda Venda { get; set; }
    }
}
